# Generated by Django 4.2.6 on 2023-12-26 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.IntegerField()),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webb.game')),
            ],
        ),
        migrations.DeleteModel(
            name='beli',
        ),
        migrations.DeleteModel(
            name='jual',
        ),
    ]
