# Generated by Django 4.2.6 on 2023-12-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0002_game_menu_delete_beli_delete_jual'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
