# Generated by Django 4.2.6 on 2023-12-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0003_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='nama',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='game_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webb.game', to_field='nama'),
        ),
    ]
