# Generated by Django 5.0 on 2023-12-29 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0004_alter_game_nama_alter_menu_game_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='unknown', max_length=255)),
                ('nominal', models.IntegerField()),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webb.game', to_field='nama')),
            ],
        ),
    ]
