# Generated by Django 5.0 on 2023-12-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0005_joki'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joki',
            old_name='item',
            new_name='paket',
        ),
        migrations.RemoveField(
            model_name='joki',
            name='game_name',
        ),
    ]
